== GET 

=== `/burgers`

The burgers path will `GET` a compelte list of available burgers. 

[%header,cols=1]
|===
|Path: https://mccabe-burger-api.herokuapp.com/burgers
|===

*Sample response*

....
[
    {
        "id": 0,
        "name": "Tribute Burger",
        "restaurant": "Honest Burgers",
        "web": "www.honestburgers.co.uk",
        "description": "A mouth-watering honest beef burger",
        "ingredients": [
            "beef",
            "american cheese",
            "burger sauce",
            "french mustard",
            "pickes",
            "onion",
            "lettuce"
        ],
        "addresses": [
            {
                "addressId": 0,
                "number": "75",
                "line1": "Venn Street",
                "line2": "Clapham",
                "postcode": "SW4 0BD",
                "country": "United Kingdom"
            }
        ]
    },
    {
        "id": 1,
        "name": "Pulled Mooshie",
        "restaurant": "Mooshies",
        "web": "www.veganburger.org",
        "description": "Spicy vegan burger with jackfruit",
        "ingredients": [
            "jackfruit",
            "coleslaw",
            "gluten free bun"
        ],
        "addresses": [
            {
                "addressId": 0,
                "number": "104",
                "line1": "Brick Lane",
                "line2": "Shoreditch",
                "postcode": "E1 6RL",
                "country": "United Kingdom"
            }
        ]
    },
    ...
]
....

NOTE : The `...` represents the remaining objects that have been omitted for brevity. 


=== `/burgers/{id}`

The `burgers/{id}` endpoint will retrieve a specfic burger or object from the database. 

[%header,cols=1]
|===
|Path: https://mccabe-burger-api.herokuapp.com/burgers/{4}
|===



*Sample response*

....
{
    "id": 4,
    "name": "Crunchy Nacho Burger",
    "restaurant": "Max Burgers",
    "web": "https://www.max.se/maten/meny/burgare/crunchy-nacho-burger/",
    "description": "The best combination of crunchiness and softness, all in one single burger",
    "ingredients": [
        "sesame bun",
        "salsa",
        "cheddar",
        "nachos",
        "beef",
        "tomato",
        "pickled onion",
        "lettuce",
        "jalapeño mayonnaise"
    ],
    "addresses": [
        {
            "addressId": 0,
            "number": "48D",
            "line1": "Skeppsbrogatan",
            "line2": "Luleå",
            "postcode": "971 25",
            "country": "Sweden"
        }
    ]
}
....

==== Status codes 

`200 OK` 

Successful response 

`404 Not Found`

Invalid path

== DELETE

=== `/burgers/{id}`

The burgers path will `DELETE` a burgers item from the database. 

[%header,cols=1]
|===
|Path: https://mccabe-burger-api.herokuapp.com/burgers/{24}
|===

*Code response*
....
curl --location --request DELETE 'https://mccabe-burger-api.herokuapp.com/burgers/24'
....

==== Status codes 

`200 OK` 

Successful response 

`404 Not Found`

Invalid path

== POST

=== `/burgers/`

Create a menu item to add to the database.

[%header,cols=1]
|===
|Path: https://mccabe-burger-api.herokuapp.com/burgers/{28}
|===

*Request Body*
....
{
        "id": 28,
        "name": "Mat Shed",
        "restaurant": "Druthers",
        "web": "www.druthers.com",
        "description": "American, Bar",
        "ingredients": [
            "beef",
            "blue cheese",
            "onion",
            "tomato",
            "red pepper",
            "lettuce"
        ],
        "addresses": [
            {
                "addressId": 0,
                "number": "2212",
                "line1": "East 6th Street",
                "line2": "New York",
                "postcode": "10029",
                "country": "United States"
}
....

==== Status codes

`201 Created`

Successful Post

*Response*

....
{
    "id": 28
}
....

== PATCH

Patch and existing menu item to update an existing value in the database. The following example is to PATCH to the `name:` field of an object in the database. 

=== `/burgers/{id}`

[%header,cols=1]
|===
|Path: https://mccabe-burger-api.herokuapp.com/burgers/{26}
|===

*Request Body*
....
{
    "name": "Gatch & Blue"
}
....

*Response*

`200 OK`

....
{
  "id": 26,
  "name": "Gatch & Blue",
  "restaurant": "Whataburger",
  "web": "www.whataburger.com",
  "description": "burger with hatch green chiles, bacon and cheese",
  "ingredients": [
    "beef",
    "cheese",
    "bacon",
    "hatch green chiles",
    "mayonnaise"
  ],
  "addresses": [
    {
      "addressId": 0,
      "number": "984",
      "line1": "388 E Stacy Rd",
      "line2": "Allen, TX",
      "postcode": "75002",
      "country": "USA"
    }
  ]
}
....

== PUT
=== `/burgers/{id}`

Use PUT method to add a field to an existing object within the database. The following example will add a secondary location address to an existing object. 

[%header,cols=1]
|===
|Path: https://mccabe-burger-api.herokuapp.com/burgers/{26}
|===

*Request body*

....
{
  "id": 26,
  "name": "Gatch & Blue",
  "restaurant": "Whataburger",
  "web": "www.whataburger.com",
  "description": "burger with hatch green chiles, bacon and cheese",
  "ingredients": [
    "beef",
    "cheese",
    "bacon",
    "hatch green chiles",
    "mayonnaise"
  ],
  "addresses": [
    {
      "addressId": 0,
      "number": "984",
      "line1": "388 E Stacy Rd",
      "line2": "Allen, TX",
      "postcode": "75002",
      "country": "USA"
    },
    {
      "addressId": 1,
      "number": "123",
      "line1": "12 E 101st St",
      "line2": "Huston, TX",
      "postcode": "77001",
      "country": "USA"
    }
  ]
}
....

*Sample response*

`200 OK`

....
{
    "id": 26,
    "name": "Gatch & Blue",
    "restaurant": "Whataburger",
    "web": "www.whataburger.com",
    "description": "burger with hatch green chiles, bacon and cheese",
    "ingredients": [
        "beef",
        "cheese",
        "bacon",
        "hatch green chiles",
        "mayonnaise"
    ],
    "addresses": [
        {
            "addressId": 0,
            "number": "984",
            "line1": "388 E Stacy Rd",
            "line2": "Allen, TX",
            "postcode": "75002",
            "country": "USA"
        },
        {
            "addressId": 1,
            "number": "123",
            "line1": "12 E 101st St",
            "line2": "Huston, TX",
            "postcode": "77001",
            "country": "USA"
        }
    ]
}
....

